version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app

version: '3'
services:
  app:
    build: .
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_PHONE_NUMBER: ${TELEGRAM_PHONE_NUMBER}
    volumes:
      - ./data:/app/data
