CREATE TABLE posts (
    post_id INTEGER PRIMARY KEY AUTOINCREMENT,
    chat_id TEXT NOT NULL,
    post_url TEXT UNIQUE NOT NULL,
    hashtags TEXT DEFAULT '',
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
